### ISSUE TITLE
ValueError: Argument must be a dense tensor

### ISSUE THREAD

**Issue by jeya-maria-jose** [nathanin/segmentation#1]
#Hey ,

I am trying GAN using CamVid database . It contains 101 images (64x64) each for input and GT. 

X_data is my input numpy array containing the data of the total batch
Shape: (101,64,64,3)

I am getting the following error:

File "tfseg.py", line 14, in <module>
    dataset = ImageMaskDataSet(features_path, labels_path)
  File "./datasets.py", line 132, in __init__
    self.image_names= tf.convert_to_tensor(X_data)
  File "/home/jose/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 836, in convert_to_tensor
    as_ref=False)
  File "/home/jose/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/jose/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/jose/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/jose/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 392, in make_tensor_proto
    _GetDenseDimensions(values)))
ValueError: Argument must be a dense tensor: [array([[[ 37,  37,  37],
        [ 31,  25,  31],
        [ 44,  26,  32],
        ..., 
        [ 86,  93, 115],
        [ 79,  83,  95],
        [ 71,  74, 132]],

       [[ 22,  22,  22],
        [ 23,  17,  21],
        [ 43,  22,  27],
        ..., 
        [ 43,  46,  56],
        [ 67,  73, 104],
        [ 81,  85, 126]],

       [[ 16,  15,  29],
        [ 27,  23,  26],
        [ 30,  12,  16],
        ..., 
        [ 58,  61, 109],
        [ 76,  74,  95],
        [ 37,  44,  57]],

       ..., 
       [[ 32,  33,  35],
        [ 35,  36,  40],
        [ 21,  22,  24],
        ..., 
        [ 38,  45,  58],
        [ 42,  44,  57],
        [ 30,  38,  46]],

       [[ 27,  27,  31],
        [ 22,  22,  26],
        [ 24,  24,  28],
        ..., 
        [ 34,  41,  52],
        [ 41,  45,  57],
        [ 44,  49,  56]],

       [[ 19,  20,  24],
        [ 23,  24,  28],
        [ 26,  27,  29],
        ..., 
        [ 37,  45,  53],
        [ 35,  43,  51],
        [ 35,  42,  53]]], dtype=uint8)] - got shape [1, 64, 64, 3], but wanted [1].

**Comment by nathanin** [comment]
Hi, 
I've ditched this repository for another: [tfmodels](https://github.com/nathanin/tfmodels). There are many optimizations to the models and especially the input pipeline. There are some [experiments](https://github.com/nathanin/tfmodels/tree/master/experiments) including GANs with MNIST data. You can write a generator for CIFAR data and replace the [MNIST dataset](https://github.com/nathanin/tfmodels/blob/4ffd99d2e65dfaa3780afc93b792404237e9e195/tfmodels/utilities/datasets/bagged_mnist.py#L174-L213). 

If you want to discuss further please make an issue at the `tfmodels` repository.

-Nathan

**Comment by jeya-maria-jose** [comment]
Hey, 
Thanks for the information
